/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual;

import java.awt.Color;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSorteio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pgrCPU = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pgrDisco = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pgrMemoria = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMinCpu = new javax.swing.JLabel();
        lblMinMemoria = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMedCpu = new javax.swing.JLabel();
        lblMedDisco = new javax.swing.JLabel();
        lblMedMemoria = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        lblMaxMemoria = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEITURA DE DADOS");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSorteio.setText("Fazer leitura dos dados");
        btnSorteio.setBorder(null);
        btnSorteio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSorteio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, 42));

        jLabel1.setText("CPU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 6, -1, -1));

        pgrCPU.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pgrCPU.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(pgrCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 34, -1, 20));

        jLabel2.setText("Disco");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, -1, -1));

        pgrDisco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(pgrDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 122, -1, -1));

        jLabel3.setText("Mémoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 194, -1, -1));

        pgrMemoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(pgrMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 224, -1, 20));

        jLabel4.setText("Minimo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 14, -1, -1));

        jLabel5.setText("Média:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 38, -1, -1));

        jLabel6.setText("Maximo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 60, -1, -1));

        jLabel7.setText("Maximo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 160, -1, -1));

        jLabel8.setText("Minimo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 116, -1, -1));

        jLabel9.setText("Média:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 138, -1, -1));

        jLabel10.setText("Média:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 238, -1, -1));

        jLabel11.setText("Maximo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 254, -1, -1));

        jLabel12.setText("Minimo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 214, -1, -1));

        lblMinCpu.setText("0");
        getContentPane().add(lblMinCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 14, -1, -1));

        lblMinMemoria.setText("0");
        getContentPane().add(lblMinMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 214, -1, -1));

        lblMinDisco.setText("0");
        getContentPane().add(lblMinDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 116, -1, -1));

        lblMedCpu.setText("0");
        getContentPane().add(lblMedCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 38, -1, -1));

        lblMedDisco.setText("0");
        getContentPane().add(lblMedDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 138, -1, -1));

        lblMedMemoria.setText("0");
        getContentPane().add(lblMedMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 238, -1, -1));

        lblMaxCpu.setText("0");
        getContentPane().add(lblMaxCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 60, -1, -1));

        lblMaxDisco.setText("0");
        getContentPane().add(lblMaxDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 160, -1, -1));

        lblMaxMemoria.setText("0");
        getContentPane().add(lblMaxMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 254, -1, -1));

        jLabel13.setText("0%");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 60, -1, -1));

        jLabel14.setText("0%");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 160, -1, -1));

        jLabel15.setText("0%");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 254, -1, -1));

        jLabel16.setText("100%");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 254, -1, -1));

        jLabel17.setText("100%");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 60, -1, -1));

        jLabel18.setText("100%");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 160, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\svgtopng\\wave.png")); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 340));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Criando variavel para gerar numeros aleatorios
    Random aleatorio = new Random();
    Integer cliques = 0;
    Integer numeroSomadoCpu = 0;
    Integer numeroSomadoDisco = 0;
    Integer numeroSomadoMemoria = 0;
  
    private void btnSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteioActionPerformed
        // TODO add your handling code here:
        cliques++;

        pgrCPU.setValue(aleatorio.nextInt(100) + 1);
        pgrCPU.setStringPainted(true);

        Integer numeroSorteadoCpu = pgrCPU.getValue();
        numeroSomadoCpu = numeroSomadoCpu + numeroSorteadoCpu;
        Integer mediaCpu = numeroSomadoCpu / cliques;
        //
        Integer numeroMenorCpu = Integer.valueOf(lblMinCpu.getText());
        Integer numeroMaiorCpu = Integer.valueOf(lblMaxCpu.getText());
        //lblMinCpu.setText(String.format("%d", numeroSorteado));

        if (cliques.equals(1)) {
            lblMinCpu.setText(String.format("%d", numeroSorteadoCpu));
        } else {
            if (numeroMenorCpu < numeroSorteadoCpu) {
                lblMinCpu.setText(String.format("%d", numeroMenorCpu));
            } else {
                lblMinCpu.setText(String.format("%d", numeroSorteadoCpu));
            }
        }

        if (numeroMaiorCpu > numeroSorteadoCpu) {
            lblMaxCpu.setText(String.format("%d", numeroMaiorCpu));
        } else {
            lblMaxCpu.setText(String.format("%d", numeroSorteadoCpu));
        }

        //lblMinCpu.setText(String.format("%d", numeroSorteado));
        lblMedCpu.setText(String.format("%d", mediaCpu));
        //lblMaxCpu.setText(String.format("%d", numeroSorteado));

        //----------------------------------------------------------------------
        pgrDisco.setValue(aleatorio.nextInt(100) + 1);
        pgrDisco.setStringPainted(true);

        //lblMinDisco.setText(String.format("%d", pgrDisco.getValue()));
        //lblMedDisco.setText(String.format("%d", pgrDisco.getValue()));
        //lblMaxDisco.setText(String.format("%d", pgrDisco.getValue()));

        Integer numeroSorteadoDisco = pgrDisco.getValue();
        numeroSomadoDisco = numeroSomadoDisco + numeroSorteadoDisco;
        Integer mediaDisco = numeroSomadoDisco / cliques;
        //
        Integer numeroMenorDisco = Integer.valueOf(lblMinDisco.getText());
        Integer numeroMaiorDisco = Integer.valueOf(lblMaxDisco.getText());
        //lblMinCpu.setText(String.format("%d", numeroSorteado));

        if (cliques.equals(1)) {
            lblMinDisco.setText(String.format("%d", numeroSorteadoDisco));
        } else {
            if (numeroMenorDisco < numeroSorteadoDisco) {
                lblMinDisco.setText(String.format("%d", numeroMenorDisco));
            } else {
                lblMinDisco.setText(String.format("%d", numeroSorteadoDisco));
            }
        }

        if (numeroMaiorDisco > numeroSorteadoDisco) {
            lblMaxDisco.setText(String.format("%d", numeroMaiorDisco));
        } else {
            lblMaxDisco.setText(String.format("%d", numeroSorteadoDisco));
        }

        //lblMinCpu.setText(String.format("%d", numeroSorteado));
        lblMedDisco.setText(String.format("%d", mediaDisco));
        //lblMaxCpu.setText(String.format("%d", numeroSorteado));

        //----------------------------------------------------------------------
        pgrMemoria.setValue(aleatorio.nextInt(100) + 1);
        pgrMemoria.setStringPainted(true);

        //lblMinMemoria.setText(String.format("%d", pgrMemoria.getValue()));
        //lblMedMemoria.setText(String.format("%d", pgrMemoria.getValue()));
        //lblMaxMemoria.setText(String.format("%d", pgrMemoria.getValue()));
        
        Integer numeroSorteadoMemoria = pgrMemoria.getValue();
        numeroSomadoMemoria = numeroSomadoMemoria + numeroSorteadoMemoria;
        Integer mediaMemoria = numeroSomadoMemoria / cliques;
        //
        Integer numeroMenorMemoria = Integer.valueOf(lblMinMemoria.getText());
        Integer numeroMaiorMemoria = Integer.valueOf(lblMaxMemoria.getText());
        //lblMinCpu.setText(String.format("%d", numeroSorteado));

        if (cliques.equals(1)) {
            lblMinMemoria.setText(String.format("%d", numeroSorteadoMemoria));
        } else {
            if (numeroMenorMemoria < numeroSorteadoMemoria) {
                lblMinMemoria.setText(String.format("%d", numeroMenorMemoria));
            } else {
                lblMinMemoria.setText(String.format("%d", numeroSorteadoMemoria));
            }
        }

        if (numeroMaiorMemoria > numeroSorteadoMemoria) {
            lblMaxMemoria.setText(String.format("%d", numeroMaiorMemoria));
        } else {
            lblMaxMemoria.setText(String.format("%d", numeroSorteadoMemoria));
        }

        //lblMinCpu.setText(String.format("%d", numeroSorteado));
        lblMedMemoria.setText(String.format("%d", mediaMemoria));
        //lblMaxCpu.setText(String.format("%d", numeroSorteado));

    }//GEN-LAST:event_btnSorteioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSorteio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMemoria;
    private javax.swing.JLabel lblMedCpu;
    private javax.swing.JLabel lblMedDisco;
    private javax.swing.JLabel lblMedMemoria;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMemoria;
    private javax.swing.JProgressBar pgrCPU;
    private javax.swing.JProgressBar pgrDisco;
    private javax.swing.JProgressBar pgrMemoria;
    // End of variables declaration//GEN-END:variables
}
